# Generated by Django 5.1.1 on 2024-09-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_Usuarios', '0002_tiendas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.CharField(max_length=100)),
                ('wr', models.CharField(max_length=100)),
                ('tkr_id', models.CharField(max_length=100)),
                ('abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_peso', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
