# Generated by Django 5.1.1 on 2024-10-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_Usuarios', '0003_datostabla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datostabla',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='datostabla',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='datostabla',
            name='tkr_id',
        ),
        migrations.AddField(
            model_name='datostabla',
            name='nui',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datostabla',
            name='peso_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='datostabla',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datostabla',
            name='tkr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datostabla',
            name='abono',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='datostabla',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='datostabla',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='datostabla',
            name='total_peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='datostabla',
            name='valor_peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='datostabla',
            name='wr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
