# Generated by Django 5.1.1 on 2024-10-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_Usuarios', '0006_remove_datostabla_nui'),
    ]

    operations = [
        migrations.AddField(
            model_name='datostabla',
            name='ISD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='datostabla',
            name='flete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
